//1
-- docker exec -it oracledb19c bash
// cd $ORACLE_HOME/network/admin
// cat sqlnet.ora
// cat tnsnames.ora
// ls -l $ORACLE_HOME/network/admin

//2
--- sqlplus / as sysdba
//show parameter;

//3
//select tablespace_name from dba_tablespaces;
//select file_name, tablespace_name from dba_data_files;
//select role from dba_roles;
//select username from dba_users;

// 4
//exit;
//env | grep ORACLE

//5
//netmgr
//tnsping YAPlab6
ALTER SESSION SET CONTAINER=FREEPDB1;
ALTER PLUGGABLE DATABASE FREEPDB1 OPEN;
CREATE USER YAPlab IDENTIFIED BY "12345";
GRANT CONNECT, RESOURCE TO YAPlab;
ALTER USER YAPlab QUOTA UNLIMITED ON USERS;
GRANT CREATE VIEW TO YAPlab;



//6

//sqlplus YAPlab/12345@//localhost:1521/FREEPDB1

CREATE TABLE t6 (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50),
    value NUMBER,
    created_at DATE DEFAULT SYSDATE
);
INSERT INTO t6 (name, value) VALUES ('1', 10);
INSERT INTO t6 (name, value) VALUES ('2', 20);
INSERT INTO t6 (name, value) VALUES ('3', 30);
INSERT INTO t6 (name, value) VALUES ('4', 40);
COMMIT;


//7
//select * from t6;

//8
//help;
//help timing;
//set timing on;
//select * from t6;
//select * from user_segments;
//set timing off;

//9
//help describe;
//desc t6;

//10
//select segment_name, segment_type, tablespace_name from user_segments;

//11
create view segment_summary as
select
  count(*) as segment_count,
  sum(extents) as total_extents,
  sum(blocks) as total_blocks,
  round(sum(bytes)/1024) as total_kilobytes
from user_segments;

select * from segment_summary;
drop view segment_summary;
