ALTER SESSION SET CONTAINER=CRS_PDB;
ALTER SESSION SET CURRENT_SCHEMA = CRS_CUR;

-- Создание ролей
CREATE ROLE ROLE_GLAV_ADMIN;
CREATE ROLE ROLE_ADMIN;
CREATE ROLE ROLE_USER;

-- GLAV_ADMIN
CREATE USER glav_admin IDENTIFIED BY Glav123
DEFAULT TABLESPACE CRS_TS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON CRS_TS;
GRANT ROLE_GLAV_ADMIN TO glav_admin;
GRANT CREATE SESSION TO glav_admin;

-- ADMIN
CREATE USER admin_user IDENTIFIED BY Admin123
DEFAULT TABLESPACE CRS_TS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON CRS_TS;
GRANT ROLE_ADMIN TO admin_user;
GRANT CREATE SESSION TO admin_user;

-- USER
CREATE USER normal_user IDENTIFIED BY User123
DEFAULT TABLESPACE CRS_TS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON CRS_TS;
GRANT ROLE_USER TO normal_user;
GRANT CREATE SESSION TO normal_user;


-- Доступы к процедурам
GRANT EXECUTE ON CRS_CUR TO ROLE_GLAV_ADMIN;
GRANT EXECUTE ON CRS_ANALYTICS TO ROLE_GLAV_ADMIN;

GRANT EXECUTE ON CRS_CUR_USER_WRAPPER TO ROLE_USER;
GRANT EXECUTE ON CRS_CUR_ADMIN_WRAPPER TO ROLE_ADMIN;


-- Роли по умолчанию
ALTER USER glav_admin DEFAULT ROLE ROLE_GLAV_ADMIN;
ALTER USER admin_user DEFAULT ROLE ROLE_ADMIN;
ALTER USER normal_user DEFAULT ROLE ROLE_USER;


-- 1. Даем доступ к директории
GRANT READ, WRITE ON DIRECTORY DATA_PUMP_DIR TO glav_admin;

-- 2. Привилегии на работу с таблицами
GRANT SELECT, INSERT, UPDATE, DELETE ON USERS TO glav_admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON ADMINS TO glav_admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON STUDIOS TO glav_admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON SERVICES TO glav_admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON STUDIO_RENT_ORDERS TO glav_admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON ARCHIVED_STUDIO_RENT_ORDERS TO glav_admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON ORDER_SERVICES TO glav_admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON ARCHIVED_ORDER_SERVICES TO glav_admin;

-- 3. Привилегии на выполнение процедур импорта/экспорта
GRANT EXECUTE ON CRS_CUR.EXPORT_USERS_TO_JSON TO glav_admin;
GRANT EXECUTE ON CRS_CUR.IMPORT_USERS_FROM_JSON_SAFE TO glav_admin;

GRANT EXECUTE ON CRS_CUR.EXPORT_STUDIOS_TO_JSON TO glav_admin;
GRANT EXECUTE ON CRS_CUR.IMPORT_STUDIOS_FROM_JSON_SAFE TO glav_admin;

GRANT EXECUTE ON CRS_CUR.EXPORT_SERVICES_TO_JSON TO glav_admin;
GRANT EXECUTE ON CRS_CUR.IMPORT_SERVICES_FROM_JSON_SAFE TO glav_admin;

GRANT EXECUTE ON CRS_CUR.EXPORT_ADMINS_TO_JSON TO glav_admin;
GRANT EXECUTE ON CRS_CUR.IMPORT_ADMINS_FROM_JSON_SAFE TO glav_admin;

GRANT EXECUTE ON CRS_CUR.EXPORT_STUDIO_RENT_ORDERS_TO_JSON TO glav_admin;
GRANT EXECUTE ON CRS_CUR.IMPORT_STUDIO_RENT_ORDERS_FROM_JSON_SAFE TO glav_admin;

GRANT EXECUTE ON CRS_CUR.EXPORT_ARCHIVED_STUDIO_RENT_ORDERS_TO_JSON TO glav_admin;
GRANT EXECUTE ON CRS_CUR.IMPORT_ARCHIVED_STUDIO_RENT_ORDERS_FROM_JSON_SAFE TO glav_admin;

GRANT EXECUTE ON CRS_CUR.EXPORT_ORDER_SERVICES_TO_JSON TO glav_admin;
GRANT EXECUTE ON CRS_CUR.IMPORT_ORDER_SERVICES_FROM_JSON_SAFE TO glav_admin;

GRANT EXECUTE ON CRS_CUR.EXPORT_ARCHIVED_ORDER_SERVICES_TO_JSON TO glav_admin;
GRANT EXECUTE ON CRS_CUR.IMPORT_ARCHIVED_ORDER_SERVICES_FROM_JSON_SAFE TO glav_admin;

GRANT EXECUTE ON CRS_CUR.EXPORT_ALL_TO_JSON TO glav_admin;
GRANT EXECUTE ON CRS_CUR.IMPORT_ALL_FROM_JSON TO glav_admin;

-- 4. Системные привилегии для работы с LOB, JSON и процедурами
GRANT CREATE PROCEDURE TO glav_admin;
GRANT CREATE TABLE TO glav_admin;
GRANT CREATE SEQUENCE TO glav_admin;
GRANT UNLIMITED TABLESPACE TO glav_admin;
GRANT EXECUTE ON DBMS_LOB TO glav_admin;
GRANT EXECUTE ON UTL_FILE TO glav_admin;

