services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: lab6-mssql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
      SA_PASSWORD: "MyPass123"
    ports:
      - "14333:1433"
    volumes:
      - ./mssql/data:/var/opt/mssql
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: lab6-nginx-sql-proxy
    depends_on:
      - mssql
    ports:
      - "15433:1433"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
