const VARIANT = 9;
const FIRST_NUMBER = 399;
const SECOND_NUMBER = 433;
const CONCATENATED_NUMBER = Number(`${FIRST_NUMBER}${SECOND_NUMBER}`);

module.exports = {
  CONCATENATED_NUMBER,
  FIRST_NUMBER,
  SECOND_NUMBER,
  VARIANT
};
